jwt:
  expire-hours: 24
  secret-key: asdf

gateway:
  ip: 127.0.0.1:8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root12#$