spring:
  datasource:
    url: jdbc:h2:mem:demo #메모리 기반
    username: sa
    password: '{cipher}616fa07d86e94ccb041c04102672188921d5daf8820afa9a9a97e82876dcc397'
    driver-class-name: org.h2.Driver
    
jwt:
  expire-hours: 24
  secret-key: asdf

order-service:
  url: http://ORDER-SERVICE-1/order-service